#!/usr/bin/env python3
"""Setup auth token for gallery-dl. Saves cookies.txt for Twitter."""

import sys

def main():
    print("=== Twitter Cookie Setup ===")
    print()
    print("In Chrome: F12 -> Application -> Cookies -> x.com")
    print("Find 'auth_token', copy its Value, paste below:")
    print()
    
    auth_token = input("auth_token: ").strip()
    
    if not auth_token:
        print("No token provided. Aborting.")
        sys.exit(1)
    
    cookie_text = f"""# Netscape HTTP Cookie File
# Generated by x-media-downloader setup
.x.com	TRUE	/	TRUE	0	auth_token	{auth_token}
"""
    
    with open("twitter-cookies.txt", "w") as f:
        f.write(cookie_text)
    
    print()
    print("✅ Saved to twitter-cookies.txt")
    print("Now run: python3 -m src.main")

if __name__ == "__main__":
    main()
